name: GitHub CI CD

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      - bugfix/*

env:
  MAIN_PYTHON_VERSION: '3.12'

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.MAIN_PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.MAIN_PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --max-attributes=11 --max-statements=59 --max-args=7 --max-branches=13 --max-positional-arguments=7 $(git ls-files '*.py')

  doc-build:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.MAIN_PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.MAIN_PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        pip install -r requirements/requirements_doc.txt
    - name: Build documentation
      run: |
        cd doc
        make html
    - name: Upload HTML documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation-html
        path: doc/_build/html
        retention-days: 7

  doc-deploy:
    needs: doc-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Clean destination folder
      run: |
        rm -rf version/dev && mkdir -p version/dev
    - name: Download HTML documentation artifact
      uses: actions/download-artifact@v4
      with:
        name: documentation-html
        path: version/dev
    - name: Update apt-get
      run: |
        sudo apt-get update
    - name: Display structure of version/dev
      run: |
        ls -R version/dev
    - name: Deploy to gh-pages branch
      if: contains(github.ref, 'refs/heads/main')
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: version/dev
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: 'DOC: Update development documentation'
        keep_files: true
        force_orphan: true
